
<div class="container">
    <div class="row">
        <h2>Payee Details</h2>
    </div>

    <div class="row">

        <div class="col-lg-8">
            <?php

            echo $this->form()->openTag($form);
            echo '<div class="form-group col-sm-3">';
            echo $this->formRow($form->get('fund_date_input'));
            echo '</div>';

            echo '<div class="form-group col-sm-3">';
            echo $this->formRow($form->get('pay_span'));
            echo '</div>';

            echo '<div class="form-group col-sm-3">';
            echo $this->formRow($form->get('direct_deposit'));
            echo '</div>';

            echo '<div class="form-group col-sm-3"><label>Calculate Due Date</label>';
            echo $this->formSubmit($form->get('due_date_submit'));
            echo '</div>';

            echo $this->form()->closeTag();

            ?>


        </div> <!-- end col -->

        <div class="col-lg-4">
            <p>
                <b>Due Date Result:</b><br>
                <div id="due_date_result"><?php //echo $this->result; ?></div>
            </p>



        </div> <!-- end col -->


    </div> <!-- end row -->





<hr>

    <div class="row">

        <div class="col-lg-8">

            <div class="calendar-wrap">

                <h4>Due Date Calendar</h4>

                <div id="calendar"></div>

            </div>


        </div> <!-- end col -->


        <div class="col-lg-4">

            <aside id="right-aside" role="complementary">

                <div class="panel panel-primary">
                    <div class="panel-heading">
                        Holidays
                    </div>
                    <div class="panel-body">
                        <ul class="list-unstyled">
                            <li> 01-01 New Year’s Day</li>
                            <li> 01-19 Martin Luther King, Jr.'s Birthday</li>
                            <li> 02-16 Washington’s Birthday</li>
                            <li> 05-25 Memorial Day</li>
                            <li> 07-03 Independence Day</li>
                            <li> 09-07 Labor Day</li>
                            <li> 10-12 Columbus Day</li>
                            <li> 11-11 Veterans Day</li>
                            <li> 11-26 Thanksgiving Day</li>
                            <li> 12-25 Christmas Day</li>
                        </ul>
                    </div>

                </div>

                <div class="panel panel-primary">
                    <div class="panel-heading">
                        Due Date Criteria
                    </div>
                    <div class="panel-body">
                        <p>This function determines the first available due date following the funding of a loan.</p>
                        <p>The paydate will be at least 10 days in the future from the fund day.</p>
                        <p>The due date will fall on a day that is a paydate based on the paydate model which is
                            specified by the pay span unless the date must be adjusted forward to miss a weekend or
                            backward to miss a holiday.</p>
                        <p>Holiday adjustment takes precedence over Weekend.</p>
                    </div>
                </div>

            </aside> <!-- end #right-aside -->

        </div> <!-- end col -->





    </div> <!-- end row -->

</div> <!-- end container -->