<div class="jumbotron">
    <h1>Pay Date Calculator</h1>
    <p><?php echo sprintf($this->translate('A Pay Date Calculator developed using Zend Framework version %s.'),  \Zend\Version\Version::VERSION) ?>
     It determines the first available due date following the funding of a loan.
        The paydate will be at least 10 days in the future from the fund day.
        The due date will fall on a day that is a paydate based on the paydate model which is specified by the pay
        span unless the date must be adjusted forward to miss a weekend or backward to miss a holiday.
        Holiday adjustment takes precedence over Weekend.
    </p>
    <p><a class="btn btn-primary btn-lg" href="/calculator/index" ><?php echo $this->translate('Calculate Due Date') ?> &raquo;</a></p>
</div>

   <div class="row">
        <div class="col-md-4">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    Relevant Files
                </div>
                <div class="panel-body">
                    <ul class="list-unstyled">
                        <li><a href="https://github.com/cgb37/zf2_heroku" target="_blank">GitHub</a></li>
                        <li><a href="https://github.com/cgb37/zf2_heroku/blob/master/module/Calculator/src/Calculator/Model/PaydateCalculator.php" target="_blank">PaydateCalculator.php</a></li>
                        <li><a href="/img/CodeChallenge.pdf" target="_blank">Requirement Diagram</a></li>
                    </ul>
                </div>
            </div>

        </div>
        <div class="col-md-4">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    Environment:  Heroku Hosting
                </div>
                <div class="panel-body">
                    <ul class="list-unstyled">
                        <li>PHP 5.6.14</li>
                        <li>Apache 2.4.17</li>
                        <li>Nginx 1.8.0</li>
                    </ul>
                </div>
            </div>

        </div>
        <div class="col-md-4">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    Technologies
                </div>
                <div class="panel-body">
                    <ul class="list-unstyled">
                        <li>Zend Framework 2</li>
                        <li>HTML5 Boilerplate</li>
                        <li>Bootstrap v3.3.1</li>
                        <li>jQuery 1.11.2</li>
                        <li>FullCalendar.js</li>
                        <li>modernizr-2.8.3</li>
                        <li>respond-1.4.2</li>
                    </ul>
                </div>
            </div>

        </div>
    </div>