<div class="jumbotron">
    <h1>Pay Date Calculator</h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-primary btn-lg" href="/calculator/index" ><?php echo $this->translate('Calculate Due Date') ?> &raquo;</a></p>
</div>

   <div class="row">
        <div class="col-md-4">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    Relevant Files
                </div>
                <div class="panel-body">
                    <ul class="list-unstyled">
                        <li><a href="https://github.com/cgb37/zf2_heroku" target="_blank">GitHub</a></li>
                        <li><a href="https://github.com/cgb37/zf2_heroku/blob/master/module/Calculator/src/Calculator/Model/PaydateCalculator.php" target="_blank">PaydateCalculator.php</a></li>
                    </ul>
                </div>
            </div>

        </div>
        <div class="col-md-4">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    Environment:  Heroku Hosting
                </div>
                <div class="panel-body">
                    <ul class="list-unstyled">
                        <li>PHP 5.6.14</li>
                        <li>Apache 2.4.17</li>
                        <li>Nginx 1.8.0</li>
                    </ul>
                </div>
            </div>

        </div>
        <div class="col-md-4">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    Technologies
                </div>
                <div class="panel-body">
                    <ul class="list-unstyled">
                        <li>Zend Framework 2</li>
                        <li>HTML5 Boilerplate</li>
                        <li>Bootstrap v3.3.1</li>
                        <li>jQuery 1.11.2</li>
                        <li>FullCalendar.js</li>
                        <li>modernizr-2.8.3</li>
                        <li>respond-1.4.2</li>
                    </ul>
                </div>
            </div>

        </div>
    </div>