<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
</div>

   <div class="row">
        <div class="col-md-4">
            <h2>Relevant Files</h2>
            <ul>
                <li><a href="https://github.com/cgb37/StarMark" target="_blank">GitHub</a></li>
            </ul>

        </div>
        <div class="col-md-4">
            <h2>Environment</h2>
            <strong>Heroku Hosting</strong>
            <ul>
                <li>PHP 5.6.14</li>
                <li>Apache 2.4.17</li>
                <li>Nginx 1.8.0</li>

            </ul>
        </div>
        <div class="col-md-4">
            <h2>Technologies</h2>
            <ul>
                <li>HTML5 Boilerplate</li>
                <li>Bootstrap v3.3.1</li>
                <li>jQuery 1.11.2</li>
                <li>modernizr-2.8.3</li>
                <li>respond-1.4.2</li>
            </ul>
        </div>
    </div>